In [ ]:

import pandas as pd
import numpy as np

In [ ]:

df=pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [6]:
# divide the dataset into features and target variables
x=df.drop('Churn',axis=1) #features
y=df['Churn']  #target
x

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5

In [7]:
y #target variable

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: object

In [8]:

#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print("taining data size:",len(x_train))
print("testing data size:",len(x_test))

taining data size: 5634
testing data size: 1409

In [10]:
#converting categorical data into numerical data
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x_train=x_train.apply(le.fit_transform)
x_test=x_test.apply(le.fit_transform)

In [11]:
#train Logistic Regression model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)
print("model trained successfully")

model trained successfully

c:\Users\nikhi\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [12]:
# calculate the m & c values
m=model.coef_[0][0]
c=model.intercept_[0]
print("m value",m)
print("c value",c)

m value -6.19150934955593e-05
c value -0.10755033042279202

In [13]:
# calculating the z value
x=5
z=m*x+c
print("for x=",x)
print("calculated z value",z)

for x= 5
calculated z value -0.10785990589026982

In [14]:
# probability

probability = 1/(1+np.exp(-z))
print("probability:",probability)
if probability > 0.6:
          print("Prediction: Pass")
else:
          print("Prediction: Fail")

probability: 0.47306113515403003
Prediction: Fail

In [15]:
#prediction
y_pred=model.predict(x_test)
print("prediction:",y_pred)

prediction: ['Yes' 'No' 'No' ... 'No' 'No' 'No']

In [16]:
#comparision
comparision=pd.DataFrame({
    "Actual":y_test.values.flatten(),
    "predicted":y_pred
})
comparision

     Actual predicted
0       Yes       Yes
1        No        No
2        No        No
3       Yes       Yes
4        No        No
...     ...       ...
1404     No        No
1405     No        No
1406     No        No
1407     No        No
1408    Yes        No

[1409 rows x 2 columns]

In [18]:

# confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[967  69]
 [219 154]]

In [19]:
#accuracy_score
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
print("accuracy:", accuracy)

accuracy: 0.7955997161107168

In [22]:
#precision_score
from sklearn.metrics import precision_score
precision=precision_score(y_test,y_pred, pos_label='Yes')
print("precision:", precision)

precision: 0.6905829596412556

In [26]:
#recall_score
from sklearn.metrics import recall_score
recall=recall_score(y_test,y_pred, pos_label='Yes')
print("recall:" ,recall)

recall: 0.4128686327077748

In [24]:
#classification_report
from sklearn.metrics import classification_report
classification=classification_report(y_test,y_pred)
print("classification:",classification)

classification:               precision    recall  f1-score   support

          No       0.82      0.93      0.87      1036
         Yes       0.69      0.41      0.52       373

    accuracy                           0.80      1409
   macro avg       0.75      0.67      0.69      1409
weighted avg       0.78      0.80      0.78      1409